name: Update Project Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for pushing

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Run dependency update script
      run: |
        # Example for Julia — replace this with your actual update command
        julia -e 'using Pkg; Pkg.update()'

    - name: Commit and push changes
      run: |
        git add -A
        git commit -m "chore: update dependencies [automated]" || echo "No changes to commit"
        git push origin HEAD

